{% set name = "s100py" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   url: https://github.com/noaa-ocs-s100/s100py/archive/refs/tags/v{{ version }}.tar.gz
   sha256: 8f51767408ffff1ab2207570114060b6ab6387a0720b94a0dacf4625a49a2301

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - h5py
    - numpy
    - gdal >=3.2

test:
  imports:
    - s100py

about:
  summary: This python package provides api and utilities for encoding hydrographic datasets in the International Hydrographic Organization (IHO) S-100 format
  home: https://github.com/noaa-ocs-s100/s100py/
  doc_url: https://s100py.readthedocs.io/en/latest/
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - erin-nagel
    - barry-gallagher
